### PR TITLE
Configurably allow access to unexported struct fields

### PR DESCRIPTION
**Pull request by jtolds**
Why would I make something so terrible possible? Because this makes luar
super useful for a live-debugging technique of enabled processes, similar
to twisted's manhole feature

https://twistedmatrix.com/documents/current/api/twisted.conch.manhole.html

### CODE REVIEW

**Comment by bontibon** [comment]
I cannot get this to work. Can you please confirm that the following test works for you (add to `example_test.go`):

```go
type Person2 struct {
	Name   string
	hidden bool
}

func Example__24() {
	const code = `
	print(p.Name)
	print(p.hidden)
	p.hidden = false
	print(p.hidden)
	`

	luar.AllowUnexportedAccesses = true
	L := lua.NewState()
	defer L.Close()

	p := Person2{
		Name:   "Tim",
		hidden: true,
	}

	L.SetGlobal("p", luar.New(L, p))

	if err := L.DoString(code); err != nil {
		panic(err)
	}
	// Output:
	// Tim
	// true
	// false
}
```

**Comment by jtolds** [comment]
Sure, so you definitely still can't do a bunch of things with unexported values, such as call them, set them, etc, but this does enable a limited amount of value reading.

This change works:

```package main

import (
	"github.com/layeh/gopher-luar"
	"github.com/yuin/gopher-lua"
)

type Person2 struct {
	Name   string
	hidden bool
}

func (p *Person2) Set(val bool) {
	p.hidden = val
}

func main() {
	const code = `
    print(p.Name)
    print(p.hidden)
    p:Set(false)
    print(p.hidden)
    `

	luar.AllowUnexportedAccesses = true
	L := lua.NewState()
	defer L.Close()

	p := &Person2{
		Name:   "Tim",
		hidden: true,
	}

	L.SetGlobal("p", luar.New(L, p))

	if err := L.DoString(code); err != nil {
		panic(err)
	}
	// Output:
	// Tim
	// true
	// false
}
```

The difference being there's a helper function for doing the value write.

**Comment by jtolds** [comment]
I mean, I admit it's definitely limited functionality (reading private values) but it's useful in a debugging context.

**Comment by bontibon** [comment]
Allowing access to unexported symbols does not seem right. I won't be merging this.

**Comment by jtolds** [comment]
I'd like to ask you to reconsider. The only reason this is even possible is because the `fmt` package allows for reading private variables. When you do fmt.Printf("%#v", val) and val is a struct, you get all the private variable names listed. That doesn't seem so bad? It's read-only.

**Comment by bontibon** [comment]
I still don't think this change belongs in the library.

I would suggest you create a custom function to aid debugging. Example:

```go
L.SetGlobal("dump", luar.New(L, func(val interface{}) {
    fmt.Printf("%#v", val)
}))
```

**Comment by jtolds** [comment]
That doesn't allow chained accesses across pointer boundaries.

In the example case I provided, p.child.Favorite.name is only possible if this change is enabled, "%#v" won't output children across pointer boundaries. Check out https://play.golang.org/p/pyUhBv_w2p

I suppose you might argue that I could make a more complex dump function that takes a chain of field accesses, and then the complex dump function could have a small DSL for understanding chained field accesses, but then I wonder what's the point of using Lua at all if I have to write a DSL anyway?

**Pull request closed without merging**
